name: primeira_pipeline
on:
  push:
    branchs: ["main"]
  workflow_dispatch:
jobs:
  primeiro_job:
    name: "meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "minha primeira acao"
        run: echo "Hello world"
      - name: "segunda acao"
        run: |
          echo "voce criou seu primeiro workflow"
          echo "parabens"
      - name: "meu primeiro python"
        run: |
          variavel = "pythonzinho"
          print(variavel)
        shell: python
  segundo_job:
    name: "instalando o ambiente de nodejs"
    runs-on: ubuntu-latest
    steps:
      - name: "verificando a versao no nodejs instalado"
        run: node --version
      - name: "definicao da versao 20.13.1 do nodejs"
      #pegar os actions no marketplace do github
      - uses: actions/setup-node@v6
        with:
          node-version: '20.13.1'
      - name: "verificando a versao no nodejs instalado"
        run: node --version
